### ISSUE TITLE
Multiple issues I could found not sure if I am running it correct way

### ISSUE THREAD

**Issue by itsparimal** [loewechiu/Print-SAP-Learning-Hub#1]
I have captured 1st slide and named it 1.pdf, but it gives me below error after running the program.

Screen size: 1920 x 1080
[]
Totally 0 slides to re-poll...
Polling Completed!
File path：C:\Users\AAI\Desktop\TEMP1\1.pdf

And the program ends with merge pdf , file not found error.
Then I changed the relist =[1] and it started working but it creates 1.pdf again and then stops.

I am not able to understand the logic here, could you please guide me.

**Comment by loewechiu** [comment]
Hi,
Sorry for a late reply.
I just updated it to an interaction mode, hope it's easy for using now.
Please try again.
